### ISSUE TITLE
Error with instructions

### ISSUE THREAD

**Issue by btemperton** [brymerr921/VirSorterParser#1]
Just ran through the instructions [here](http://merenlab.org/2018/02/08/importing-virsorter-annotations), for our data. The tools worked great, but there is a slight error in one of the commands for exporting gene calls:
```
anvi-anvi-export-gene-calls CONTIGS.db \
                  -o all_gene_calls.txt
```

should be 

```
anvi-export-gene-calls -c CONTIGS.db \
                  -o all_gene_calls.txt
```

**Comment by meren** [comment]
fixed :) thank you very much!
