### ISSUE TITLE
virsorter_to_anvio.py 

### ISSUE THREAD

**Issue by tdelmont** [brymerr921/VirSorterParser#2]
Hi,

I have been following the post for virsorter usage within anvi'o, and I get this error with the virsorter_to_anvio.py:

```
python ./virsorter_to_anvio.py -a VIRSorter_affi-contigs.tab -g VIRSorter_global-phage-signal.csv -s splits_basic_info.txt --db 2 --anvio-gene-calls all_gene_calls.txt --hallmark-functions db2_hallmark_functions.txt
Traceback (most recent call last):
  File "./virsorter_to_anvio.py", line 392, in <module>
    hf = hf+(" (non-Caudovirales)")
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
```

Any thoughts ? 

Many thanks,

Tom

**Comment by brymerr921** [comment]
Hi Tom,

Based on my best guess, you actually ran VirSorter on database 1, and should in fact be specifying `--db 1` and `--hallmark-functions db1_hallmark_functions.txt`. Is it possible this is what happened? I suggest trying the parser with these options and see if it completes.

What's going on here is that when the parser reads in `db2_hallmark_functions.txt`, it populates a dictionary (`f_dict`). Though there are some overlaps between phage cluster names in `db2_hallmark_functions.txt` and `db1_hallmark_functions.txt`, there are some differences. Therefore, if you have VirSorter output from db1 and want to run this parser but select `db2_hallmark_functions.txt`, some of the phage clusters from the db1 output that are hallmarks there don't exist in `db2_hallmark_functions.txt`. In this case, line 389 returns an empty dictionary, causing line 391 to throw throw precisely the error you described.

Best,
Bryan

**Comment by tdelmont** [comment]
Hi Bryan,

That worked perfectly, many thanks!
What happened is that I followed the commands provided in the blog, including the last example for the parser, assuming it was coherent with the default previous command lines. My mistake.

Best,

Tom
